nfc_card_game/main/color_match/urls.py
from nfc_card_game.main.color_match import controls
from nfc_card_game.main.color_match.color import color_overview, rules
from django.urls import path

color_urlpatterns = [
    path("", rules, name=("rules")),
    path("overview", color_overview, name="color_overview"),
    path("reset", controls.reset_and_start_game, name="color_reset"),
    path("stop", controls.stop_game, name="color_stop"),
    path("start", controls.start_game, name="color_start"),
]

nfc_card_game/main/urls.py
from django.urls import include, path

from . import api
from . import views
from . import game_loop
from nfc_card_game.main.color_match.urls import color_urlpatterns

urlpatterns = [
    path("", views.index, name="index"),
    path("player/<str:card_uuid>", views.player, name="player"),
    path("post/<str:card_uuid>", views.post, name="post"),
    path("vossenjacht", views.vossenjacht, name="vossenjacht"),
    path("dashboard", views.dashboard, name="dasbhoard"),
    path("mine/<str:card_uuid>", views.mine, name="mine"),
    path("register-player/", views.register_player, name="register-player"),
    path("stop-game-loop", game_loop.stop_scheduler, name="stop-game-loop"),
    path("start-game-loop", game_loop.start_scheduler, name="start-game-loop"),
    path("clear-session", views.clear_session, name="clear-session"),
    path("api/dashboard", api.dashboard, name="api/dashboard"),
    path("api/dashboard/<int:mine_id>", api.dashboard_mine, name="api/dashboard-mine"),
    path("color/", include(color_urlpatterns)),
]

nfc_card_game/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("nfc_card_game.main.urls")),
    path("admin/", admin.site.urls),
    path("", include("pwa.urls")),
]

nfc_card_game/main/color_match/models.py
from django.db import models


class ColorMatchGameState(models.TextChoices):
    RUNNING = "RUNNING"
    STOPPED = "STOPPED"


class ColorMatchSettings(models.Model):
    game_state = models.CharField(
        choices=ColorMatchGameState, default=ColorMatchGameState.RUNNING
    )
    auto_rotate_colors = models.BooleanField(default=False)

    @classmethod
    def object(cls):
        return cls._default_manager.all().first()  # Since only one item

nfc_card_game/main/models/activities.py
from django.db import models

from nfc_card_game.main.models.utils import short_uuid


class Activity(models.Model):
    name = models.CharField(max_length=100)
    card_uuid = models.CharField(default=short_uuid, max_length=10)

    def __str__(self):
        return self.name

nfc_card_game/main/models/game_settings.py
from django.db import models


class GameSettings(models.Model):
    class GameMode(models.TextChoices):
        TRADING = "trading"
        ACTIVITIES = "activiteiten"
        VOSSENJACHT = "vossen"
        COLOR = "color"

    mode = models.CharField(choices=GameMode, default=GameMode.TRADING, max_length=50)

    @classmethod
    def object(cls):
        return cls._default_manager.all().first()  # Since only one item

    def __str__(self):
        return f"{self.mode=}"

nfc_card_game/main/models/trading.py
from django.db import models

from .player import Player, Team
from .utils import short_uuid


class TypeType(models.TextChoices):
    COIN = "COIN", "Coin"
    RESOURCE = "RESOURCE", "Resource"
    MINER = "MINER", "Miner"


class CoinType(models.TextChoices):
    BLAUW = "Blauw", "\U0001f535"
    GROEN = "Groen", "\U0001f7e2"
    ROOD = "Rood", "\U0001f534"


class ResourceType(models.TextChoices):
    A = "BIJL", "Bijl"
    B = "TANDWIEL", "Tandwiel"
    C = "RUPSBAND", "Rupsband"


class MinerType(models.TextChoices):
    A = "MIJNWERKER", "Mijnwerker"
    B = "DRILBOOR", "Drilboor"
    C = "BULLDOZER", "Bulldozer"


class Item(models.Model):
    name = models.CharField(
        choices=list(ResourceType.choices)
        + list(CoinType.choices)
        + list(MinerType.choices)
    )
    type = models.CharField(choices=TypeType)
    currency = models.CharField(choices=CoinType)

    def save(self, *args, **kwargs):
        if self.name in dict(ResourceType.choices):
            self.type = TypeType.RESOURCE
        elif self.name in dict(CoinType.choices):
            self.type = TypeType.COIN
        elif self.name in dict(MinerType.choices):
            self.type = TypeType.MINER
        super(Item, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.currency}: {self.name}"


class PlayerItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    amount = models.BigIntegerField()

    class Meta:
        unique_together = ("player", "item")

    def __str__(self):
        return f"Player: {self.player} with Item: {self.item} x {self.amount}"


class Mine(models.Model):
    card_uuid = models.CharField(default=short_uuid, max_length=10)
    name = models.CharField(max_length=100, choices=CoinType)
    currency = models.CharField(max_length=100, choices=CoinType)

    class Meta:
        unique_together = ("currency",)

    def save(self, *args, **kwargs):
        created = not self.pk
        super().save(*args, **kwargs)
        if created:
            for team in Team.objects.all():
                TeamMine.objects.create(team=team, mine=self, amount=100)

    def __str__(self):
        return f"{self.name} currency: {self.currency}"


class TeamMine(models.Model):
    mine = models.ForeignKey(Mine, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    money = models.BigIntegerField()

    class Meta:
        unique_together = ("mine", "team")

    def __str__(self):
        return f"{self.team}: {self.mine}"


class TeamMineItem(models.Model):
    team_mine = models.ForeignKey(TeamMine, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    amount = models.BigIntegerField(default=0)

    class Meta:
        unique_together = ("team_mine", "item")


class ItemType(models.TextChoices):
    RESOURCE = "RESOURCE", "Resource"
    MINER = "MINER", "Miner"


class Post(models.Model):
    card_uuid = models.CharField(default=short_uuid, max_length=10)
    name = models.CharField(max_length=100)
    type = models.CharField(choices=ItemType)
    sells = models.ForeignKey(Item, on_delete=models.CASCADE)
    sell_amount = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return f"Post {self.name}: "


class PostRecipe(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    price = models.IntegerField()

    class Meta:
        unique_together = ("post", "item")

nfc_card_game/main/models/utils.py
import uuid


def short_uuid() -> str:
    return str(uuid.uuid4())[:8]

nfc_card_game/main/forms.py
from django import forms


from nfc_card_game.main.models.player import Player


class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ["card_uuid", "name", "section", "team"]

nfc_card_game/main/views.py
import math

from django.core import serializers
from django.db.models import Sum
from django.http import Http404, HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_list_or_404, get_object_or_404, render

from nfc_card_game.main.color_match.color import handle_color_player
from nfc_card_game.main.color_match.color import post_color
from nfc_card_game.main.forms import PlayerForm
from nfc_card_game.main.models.activities import Activity
from nfc_card_game.main.models.game_settings import GameSettings
from nfc_card_game.main.models.trading import TypeType

from .logic import (
    get_resource_price,
    handle_mine_scan,
    handle_miner_scan,
    handle_post_scan,
)
from .models.player import Player
from .models.trading import Mine, PlayerItem, Post, PostRecipe, TeamMine, TeamMineItem

ABS_SELL_OPTIONS = [1, 5, 10, 20, 50, 100, 500, 1000, 5000, 10000]
REL_SELL_OPTIONS = {1: "100%", 0.5: "50%", 0.25: "25%"}


def index(request):
    return HttpResponse("Scan een kaartje met je telefoon!")


def thanks(request, card_uuid):
    return render(request, "thanks.html")


def get_player_register(request: HttpRequest, card_uuid: str):
    player_instance, _ = Player.objects.get_or_create(card_uuid=card_uuid)
    form = PlayerForm(instance=player_instance)
    return render(request, "register.html", {"form": form})


def handle_activities_player(
    request: HttpRequest, player: Player, game_mode: GameSettings.GameMode
) -> HttpResponse:
    if act_uuid := request.session.get("post"):
        if act_uuid == "vote":
            return render(request, "activities/vote.html")

        activity = Activity.objects.get(card_uuid=act_uuid)
        player.activities.add(activity)

    all_activities = {act: False for act in Activity.objects.all()}
    player_activities = list(player.activities.all())
    for player_act in player_activities:
        all_activities[player_act] = True

    if game_mode == GameSettings.GameMode.VOSSENJACHT:
        all_activities = {act: True for act, value in all_activities.items() if value}

    return render(
        request,
        "activities/overview.html",
        {
            "player_activities": all_activities,
            "player": player,
            "title": game_mode,
        },
    )


def handle_trading_player_post(request, player: Player, items, player_item):
    selected_amount = int(request.POST.get("amount", 1))
    price = request.session.get("price")
    player.name = player.name.split(" ")[0]
    context = {"buy_amount": selected_amount, "items": items, "player": player}
    if post_uuid := request.session.get("post"):
        post = PostRecipe.objects.filter(post__card_uuid=post_uuid)
        context["post"] = post
        if post[0].post.type == TypeType.MINER:
            action = handle_miner_scan(player, post, player_item, selected_amount)

        elif post[0].post.type == TypeType.RESOURCE:
            action = handle_post_scan(player, post, player_item, price, selected_amount)

    action_dict = action.model_dump() if action else None
    context["action"] = action_dict
    return render(request, "trading/player_bought.html", context)


def handle_trading_player(request: HttpRequest, player: Player) -> HttpResponse:
    player_items = PlayerItem.objects.filter(player=player).order_by(
        "item__currency", "item__name"
    )
    team_mines = TeamMine.objects.filter(team=player.team)

    if request.method == "POST":
        return handle_trading_player_post(request, player, player_items, player_items)

    player.name = player.name.split(" ")[0]
    context = {"player": player, "items": player_items}
    request.session.pop("price", None)

    absolute_sell_options = {}
    relative_sell_options = {}

    if post_uuid := request.session.get("post"):
        post = PostRecipe.objects.filter(post__card_uuid=post_uuid)
        context["post"] = post

        if post[0].post.type == TypeType.RESOURCE:
            total_money = (
                player_items.filter(item__type=TypeType.COIN)
                .exclude(item__currency=post.first().post.sells.currency)
                .aggregate(Sum("amount"))["amount__sum"]
            )
            price = get_resource_price(team_mines, post[0].post.sells)
            context["price"] = price
            request.session["price"] = price

            absolute_sell_options = {
                sell_option: sell_option * price
                for sell_option in ABS_SELL_OPTIONS
                if sell_option * price <= total_money
            }

            relative_sell_options = {
                math.floor((total_money / price) * factor): text
                for factor, text in REL_SELL_OPTIONS.items()
            }

        if post[0].post.type == TypeType.MINER:
            min_item_amount = min(
                player_items.get(item=recipe.item).amount for recipe in post
            )

            absolute_sell_options = {
                sell_option: sell_option * sell_option
                for sell_option in ABS_SELL_OPTIONS
                if sell_option * sell_option <= min_item_amount
            }

            relative_sell_options = {
                math.floor(min_item_amount * factor): text
                for factor, text in REL_SELL_OPTIONS.items()
            }

    if mine_uuid := request.session.get("mine"):
        mine = TeamMine.objects.filter(mine__card_uuid=mine_uuid, team=player.team)
        mine_items = TeamMineItem.objects.filter(team_mine__mine__card_uuid=mine_uuid)
        context["post"] = mine
        context["mine"] = mine
        action = handle_mine_scan(player, player_items, mine, mine_items)
        context["action"] = action.model_dump() if action else None

    absolute_sell_options.pop(0, None)
    relative_sell_options.pop(0, None)
    context["buy_amounts_abs"] = sorted(absolute_sell_options.items())
    context["buy_amounts_rel"] = sorted(relative_sell_options.items())

    return render(request, "trading/player_stats.html", context)


def player(request: HttpRequest, card_uuid: str) -> HttpResponse:
    try:
        player = Player.objects.get(card_uuid=card_uuid)
    except Player.DoesNotExist:
        player = None

    if player is None or player.name == "" or player.team is None:
        return get_player_register(request, card_uuid)

    game_mode = GameSettings.object().mode
    if game_mode == GameSettings.GameMode.TRADING:
        return handle_trading_player(request, player)

    if game_mode in [
        GameSettings.GameMode.ACTIVITIES,
        GameSettings.GameMode.VOSSENJACHT,
    ]:
        return handle_activities_player(request, player, game_mode)

    if game_mode == GameSettings.GameMode.COLOR:
        return handle_color_player(request, player)


def register_player(request: HttpRequest):
    player_instance = Player.objects.get(card_uuid=request.POST["card_uuid"])
    if request.method == "POST":
        form = PlayerForm(request.POST, instance=player_instance)
        if form.is_valid():
            player = form.save()
            return HttpResponseRedirect(f"/player/{player.card_uuid}")
        return HttpResponse(form.errors.as_json())

    raise Http404


def mine(request: HttpRequest, card_uuid: str) -> HttpResponse:
    mine = get_object_or_404(Mine, card_uuid=card_uuid)
    request.session["mine"] = mine.card_uuid
    request.session.pop("post", None)

    return render(request, "trading/mine.html", {"mine": mine})


def post_trading(request, card_uuid: str) -> HttpResponse:
    post = get_object_or_404(Post, card_uuid=card_uuid)
    buys = get_list_or_404(PostRecipe, post=post.pk)
    request.session["post"] = post.card_uuid
    request.session.pop("mine", None)

    return render(request, "trading/post.html", {"post": post, "buys": buys})


def post_activities(request: HttpRequest, card_uuid: str) -> HttpResponse:
    if card_uuid == "vote":
        request.session["post"] = card_uuid
        return render(request, "msg.html", {"text": "logged in as stembus"})

    activity = get_object_or_404(Activity, card_uuid=card_uuid)
    request.session["post"] = card_uuid
    return render(request, "msg.html", {"text": f"logged in as {activity.name}"})


def post(request: HttpRequest, card_uuid: str) -> HttpResponse:
    game_mode = GameSettings.object().mode
    if game_mode == GameSettings.GameMode.TRADING:
        return post_trading(request, card_uuid)

    if game_mode == GameSettings.GameMode.COLOR:
        return post_color(request, card_uuid)

    if game_mode in [
        GameSettings.GameMode.ACTIVITIES,
        GameSettings.GameMode.VOSSENJACHT,
    ]:
        return post_activities(request, card_uuid)


def dashboard(request: HttpRequest) -> HttpResponse:
    pi = serializers.serialize("json", PlayerItem.objects.all())
    tm = TeamMine.objects.all().order_by("team", "mine__currency")
    tmi = TeamMineItem.objects.all().order_by(
        "team_mine__team", "item__currency", "item"
    )
    data = {"player_items": pi, "team_mines": tm, "team_mine_items": tmi}
    return render(request, "trading/dashboard.html", data)


def clear_session(request: HttpRequest) -> HttpResponse:
    request.session.pop("post", None)
    request.session.pop("mine", None)
    return render(request, "msg.html", {"text": "Cleared session"})


def vossenjacht(request: HttpRequest) -> HttpResponse:
    players = Player.objects.all()

    overview = []
    for player in players:
        num_activities = player.activities.count()
        if not num_activities:
            continue
        overview.append(
            (
                player.name,
                num_activities,
                ", ".join([str(activity) for activity in player.activities.all()]),
            )
        )
    overview = sorted(overview, key=lambda x: x[1], reverse=True)

    return render(request, "activities/all.html", {"player_infos": overview})

nfc_card_game/main/templates/trading/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ player.name }}{% endblock %}

{% block content %}

  <div class="container pt-2">
    <div class="accordion card shadow">
      <div class="card-header align-items-center">
        <h3 class="m-0">Overzicht</h3>
      </div>
      <div class="card-body">
        <canvas id="mineChart"></canvas>
      </div>
    </div>
  </div>

  <div class="container pt-2">
    <div class="accordion card shadow">
      <div class="card-header align-items-center">
        <h3 class="m-0">Overzicht</h3>
      </div>
      <div class="card-body">
        <canvas id="minerChart"></canvas>
    </div>
  </div>

  <div class="container pt-2">
    <div class="card shadow w-100" style="width: 100%">
      <div class="card-header align-items-center">
        <h3 class="m-0">Mines</h3>
      </div>
      <div class="card-body">
        <div class="table-responsive">
        <table class="table table-striped table-responsive">
          <thead>
            <tr>
              <th>Mine</th>
              <th>Team</th>
              <th>currency</th>
              <th>Amount</th>
            <tr>
          </thead>
          <tbody id="team_table">
            {% for team in team_mines %}
              <tr>
                <td>{{ team.mine.name }}</td>
                <td>{{ team.team }}</td>
                <td>{{ team.mine.currency }}</td>
                <td id="{{ team.team.id }}_{{ team.mine.currency }}">{{ team.money }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>

        </div>
      </div>
    </div>
  </div>

  <div class="container pt-2">
    <div class="accordion card shadow">
      <div class="card-header align-items-center">
        <h3 class="m-0">Logs</h3>
      </div>
      <div class="card-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Speler</th>
              <th>Koopt</th>
              <th>Voor</th>
              <th>Actie</th>
            <tr>
          </thead>
          <tbody id="logtable">
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <script>
    var player_items = JSON.parse('{{ player_items|safe}}');
    var team_info = [];
    var mine_items = [];

    {% for item in team_mines %}
      var object = {
        team_id: {{ item.id }},
        mine_id: {{ item.mine.id }},
        mine: "{{ item.mine }}",
        type: "{{ item.type }}",
        currency: "{{ item.mine.currency }}",
        team: "{{ item.team }}",
        mine_amount: "{{ item.money }}"
      };
    team_info.push(object);
    {% endfor %}

    {% for item in team_mine_items %}
      var object = {
        item: "{{ item.item }}",
        mine: "{{ item.team_mine.mine }}",
        team: "{{ item.team_mine.team }}",
        amount: "{{ item.amount }}",
      }
    mine_items.push(object)
    {% endfor %}


  </script>
  <script src={% static 'dashboard.js' %}></script>

{% endblock content %}

nfc_card_game/main/templates/trading/inventory.html
<div class="container pt-2">
    <div class="accordion card shadow">
        <div class="card-header align-items-center">
            <h4 class="m-0">{{ player.name }} | {{ player.section }} | {{ player.team }}</h4>
        </div>
        <div class="card-body">
            <table class="table table-striped table-m">
                <thead>
                    <tr>
                        <th scope="col" class="col-2">Munt</th>
                        <th scope="col" class="col-1">Hoeveelheid</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {% for item in items %}
                    {% if item.item.type == "COIN" %}
                    <tr>
                        <td>{{ item.item.get_currency_display }} {{ item.item.name }}</td>
                        <td>{{ item.amount}}</td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col" class="col-2">Item</th>
                        <th scope="col" class="col-1">Hoeveelheid</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {% for item in items %}
                    {% if item.item.type != "COIN" and item.amount %}
                    <tr>
                        <td>{{ item.item.get_currency_display }} {{ item.item.get_name_display }}</td>
                        <td>{{ item.amount }}</td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

nfc_card_game/main/templates/trading/mine.html
{% extends "base.html" %}

{% block title %}Post Page{% endblock %}

{% block content %}

<div class="container pt-2">
  <div class="accordion card shadow">
    <div class="card-header align-items-center">
      <h3 class="m-0">Aangemeld als Mine: {{ mine.name }}</h3>
    </div>
    <div class="card-body">
      <p>{{ mine }}</p>
      <p>{{ mine.currency }}</p>
      <p>{{ mine.team }}</p>
      <p>{{ mine.amount }}</p>
    </div>
  </div>
</div>

{% endblock %}

nfc_card_game/main/templates/trading/player_bought.html
{% extends "base.html" %}
{% load static %}


{% block title %}{{ player.name }}{% endblock %}

{% block content %}
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.0/font/bootstrap-icons.css">
  <link rel="shortcut icon"  href="{% static '/images/favicon.png' %}">
</head>

<body>
  <div class="container pt-2">
    <div class="card shadow">
        <div class="card-header">
          <h4 class="card-title"><span class="bi-cart-check-fill h3"></span> {{ post.0.post.sells.get_currency_display }}{{ post.0.post.name }}</h4>
        </div>
      <div class="card-body">
        {% if action.status == "ok" %}
        <h4>Je hebt {{ buy_amount }}x {{ action.bought.item.get_currency_display }}{{ action.bought.item.get_name_display }} gekocht!</h4>
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Gekocht:</th>
              <th scope="col">Voor:</th>
            </tr>
          </thead>
          <tbody>
            {% for key, val in action.costs.items %}
            <tr>
              {% if forloop.counter0 == 0 %}
                {% if action.bought.item != None %}
                <td class="table-success">{{ action.bought.amount }}x {{ action.bought.item.get_currency_display }}{{ action.bought.item.get_name_display}}</td>
                {% else %}
                  <td></td>
                {% endif %}
              {% else %}
                <td></td>
              {% endif %}
              <td class="table-danger">{{ val.amount }}x {{ val.currency }}{{ val.name }}</td>
            <tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
          <div class="alert alert-danger" role="alert">
            {{ action.status }}: {{ action.log }}
          </div>
        {% endif %}
      </div>
    </div>
  </div>
  {% include "trading/inventory.html" %}

</body>


{% endblock content %}

nfc_card_game/main/templates/trading/player_stats.html
{% extends "base.html" %}
{% load static %}


{% block title %}{{ player.name }}{% endblock %}

{% block content %}

<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.0/font/bootstrap-icons.css">
  <link rel="shortcut icon" href="{% static '/images/favicon.png' %}">
</head>

<body>
  <div class="container pt-2">
    <div class="card shadow">
      <div class="card-header">
        {% if mine %}
          <h4 class="card-title"><span class="bi-minecart-loaded h2" style="filter: invert(0%)"></span>  Welkom bij mine {{ mine.0.mine.get_currency_display }}{{ mine.0.mine.currency }}</h4>
        {% elif post %}
          <h4 class="card-title"><span class="bi-shop h2"></span> Welkom bij {{ post.0.post.sells.get_currency_display }}{{post.0.post.name }}</h4>
        {% endif %}
      </div>
      <div class="card-body">
        {% if mine %}
            {% if action.status == "ok" %}
              <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">Geld gekregen:</th>
                    <th scope="col">Afgevelerd:</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    {% if action.bought.item != None %}
                      <td class="table-success">{{ action.bought.amount }}x {{action.bought.item.get_name_display}}{{ action.bought.item.name }}</td>
                    {% else %}
                      <td></td>
                    {% endif %}
                    {% for key, val in action.costs.items %}
                      {% if forloop.counter0 == 0 %}
                      {% else %}
                        <td></td>
                      {% endif %}
                      <td class="table-danger">{{ val.amount }}x {{ val.currency }}{{ val.name }}</td>
                      <tr>
                    {% endfor %}
                </tbody>
              </table>
          {% else %}
            <p>{{ action.status }}: {{ action.log }}</p>
          {% endif %}
        {% elif post %}
          {% if buy_amounts_abs %}
            <h5>Hoeveel {{ post.0.post.sells.get_currency_display }}{{post.0.post.sells.get_name_display}} wil je kopen?</h5>
            {% if price %} <h5>Prijs: {{ price }}</h5>{% endif %}
            <form method="post">
              {% csrf_token %}
              <div class="d-flex align-items-start justify-content-start flex-row flex-wrap">
              {% for amount, text in buy_amounts_abs %}
                <button class="btn btn-primary m-2 d-block w-25" style="height: 62px;" type="submit" name="amount" value="{{ amount }}">
                  {{ amount }}x </br>{% if text %} ({{ text }}) {% endif %}
                </button>
              {% endfor %}
              </div>
              <!-- <hr> -->
              <div class="d-flex align-items-start justify-content-start flex-row flex-wrap">
                {% for amount, text in buy_amounts_rel %}
                  <button class="btn btn-info m-2 d-block w-25" style="height: 62px;" type="submit" name="amount" value="{{ amount }}">
                    {{ amount }}x </br>{% if text %} ({{ text }}) {% endif %}
                  </button>
                {% endfor %}
                </div>
            </form>
          {% else %}
            <div class="alert alert-danger" role="alert">
              Je kan hier niks kopen!
            </div>
          {% endif %}
        {% else %}
          <h4 class="card-title"><span class="bi-cart4 h2" style="filter: invert(0%)"></span>         Deze items heb jij nu:</h4>
        {% endif %}
      </div>
    </div>
  </div>
{% include "trading/inventory.html" %}
</body>


{% endblock content %}

nfc_card_game/main/templates/trading/post.html
{% extends "base.html" %}

{% block title %}Post Page{% endblock %}

{% block content %}

<div class="container pt-2">
  <div class="accordion card shadow">
    <div class="card-header align-items-center">
      <h3 class="m-0">Aangemeld als {{ post.name }}, dit verkoop jij</h3>
    </div>
    <div class="card-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th colspan="2" scope="col">Verkoop</th>
            <th style="border-left: 1px solid #000" colspan="2" scope="col">Voor</th>
          </tr>
        </thead>
        <tbody>
          {% for item in buys %}
            <tr>
              {% if forloop.counter0 == 0 %}
                <td>{{ post.sell_amount}}</td>
                <td>{{ post.sells }}</td>
              {% else %}
                <td colspan="2"></td>
              {% endif %}
              <td style="border-left: 1px solid #000">{{ item.amount }}</td>
              <td>{{ item.item }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
  </div>
</div>

{% endblock %}